# Basics of `NumPy`
### Dr. Tirthajyoti Sarkar, Fremont, CA 94536
---
This Notebook provides absolute basics of the `NumPy` package, which is the core numerical computing package in the Python ecosystem. `NumPy` contains **single or multi-dimentional array** and **matrix** data structures. It can be utilized to perform a number of mathematical operations on arrays such as trigonometric, statistical, and algebraic routines.

`NumPy` also provides functionality for basic descriptive statistics, linear algebra, and is used by other core data science libraries such as `Pandas`, `Scikit-learn`, and `TensorFlow`. 

### Create a Numpy array (from a list)

In [1]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)

In [2]:
type(array1)

numpy.ndarray

In [3]:
type(lst1)

list

In [4]:
array1

array([1, 2, 3])

### Add two Numpy arrays (and note the difference with `list`s)

In [5]:
lst2 = lst1 + lst1
print("Two Python lists added together: ",lst2)

Two Python lists added together:  [1, 2, 3, 1, 2, 3]


In [6]:
array2 = array1 + array1
print("Two NumPy arrays added together: ",array2)

Two NumPy arrays added together:  [2 4 6]


### Simple arithmatic operations on Numpy arrays

In [7]:
print("array1 multiplied by array2: ",array1*array2)
print("array1 divided by array2: ",array1/array2)
print("array1 raised to the power of array2: ",array1**array2)

array1 multiplied by array2:  [ 2  8 18]
array1 divided by array2:  [0.5 0.5 0.5]
array1 raised to the power of array2:  [  1  16 729]


### More advanced mathematical operations on Numpy arrays

In [8]:
lst_3=[i for i in range(1,6)]
print(lst_3)
array_3=np.array(lst_3)

[1, 2, 3, 4, 5]


In [9]:
# sine function
print("Sine: ",np.sin(array_3))

Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [10]:
# logarithm
print("Natural logarithm: ",np.log(array_3))
print("Base-10 logarithm: ",np.log10(array_3))
print("Base-2 logarithm: ",np.log2(array_3))

Natural logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base-10 logarithm:  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Base-2 logarithm:  [0.         1.         1.5849625  2.         2.32192809]


In [11]:
# Exponential
print("Exponential: ",np.exp(array_3))

Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### How to generate arrays easily? `arange` and `linspace`

In [12]:
print("A series of numbers:",np.arange(5,16))
print("Numbers spaced apart by 2:",np.arange(0,11,2))
print("Numbers spaced apart by float:",np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ",np.arange(30,-1,-5))

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]
Numbers spaced apart by 2: [ 0  2  4  6  8 10]
Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]


In [13]:
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


### Creating multi-dimensional array

In [14]:
# From a list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [15]:
# From a tuple
my_tuple = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(my_tuple)
print (mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


### Dimension, shape, size, and data type of the 2D array

In [16]:
print("Dimension of this matrix: ",mat.ndim,sep='') 
print("Size of this matrix: ", mat.size,sep='') 
print("Shape of this matrix: ", mat.shape,sep='')
print("Data type of this matrix: ", mat.dtype,sep='')

Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


### Zeros, Ones, Random, and Identity Matrices and Vectors

In [17]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5’s:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]
Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix of shape (4,3):
 [[2 1 1]
 [5 8 5]
 [9 5 3]
 [3 6 5]]


### Exercise 9: Reshaping, Ravel, Min, Max, Sorting

In [18]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [19]:
print("\na looks like\n",a)
print("\nb looks like\n",b)
print("\nc looks like\n",c)


a looks like
 [86 98 67 79 97 55 70 85 24 11 74 99 83 87 77 27 13 14 69 20 15 76 35 93
 97 43 82 23 76 89]

b looks like
 [[[86 98 67 79 97]
  [55 70 85 24 11]
  [74 99 83 87 77]]

 [[27 13 14 69 20]
  [15 76 35 93 97]
  [43 82 23 76 89]]]

c looks like
 [[86 98 67 79 97]
 [55 70 85 24 11]
 [74 99 83 87 77]
 [27 13 14 69 20]
 [15 76 35 93 97]
 [43 82 23 76 89]]


In [20]:
b_flat = b.ravel()
print(b_flat)

[86 98 67 79 97 55 70 85 24 11 74 99 83 87 77 27 13 14 69 20 15 76 35 93
 97 43 82 23 76 89]


### Indexing and slicing

In [21]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr2 = np.arange(0,21,2)
print("New array:",arr2)
print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [22]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
 [[67 15 30 32 76]
 [75 32 88 86 80]
 [55 55 81 96 44]]

Double bracket indexing

Element in row index 1 and column index 2: 88

Single bracket with comma indexing

Element in row index 1 and column index 2: 88

Row or column extract

Entire row at index 2: [55 55 81 96 44]
Entire column at index 3: [32 86 96]

Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[86 80]
 [96 44]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[15 32]
 [32 86]]


### Conditional subsetting

In [23]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nElements greater than 50\n", mat[mat>50])

Matrix of random 2-digit numbers
 [[96 17 44 77 49]
 [82 25 63 23 66]
 [12 39 95 34 29]]

Elements greater than 50
 [96 77 82 63 66 95]


### Array operations (array-array, array-scalar, universal functions)

In [24]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)

print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
 [[7 7 7]
 [5 4 5]
 [3 3 5]]

2nd Matrix of random single-digit numbers
 [[6 8 6]
 [3 9 7]
 [1 6 4]]

Addition
 [[13 15 13]
 [ 8 13 12]
 [ 4  9  9]]

Multiplication
 [[42 56 42]
 [15 36 35]
 [ 3 18 20]]

Division
 [[1.16666667 0.875      1.16666667]
 [1.66666667 0.44444444 0.71428571]
 [3.         0.5        1.25      ]]

Lineaer combination: 3*A - 2*B
 [[ 9  5  9]
 [ 9 -6  1]
 [ 7 -3  7]]

Addition of a scalar (100)
 [[107 107 107]
 [105 104 105]
 [103 103 105]]

Exponentiation, matrix cubed here
 [[343 343 343]
 [125  64 125]
 [ 27  27 125]]

Exponentiation, sq-root using pow function
 [[2.64575131 2.64575131 2.64575131]
 [2.23606798 2.         2.23606798]
 [1.73205081 1.73205081 2.23606798]]


### Stacking arrays

In [25]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Matrix a\n",a)
print("Matrix b\n",b)
print("Vertical stacking\n",np.vstack((a,b)))
print("Horizontal stacking\n",np.hstack((a,b)))

Matrix a
 [[1 2]
 [3 4]]
Matrix b
 [[5 6]
 [7 8]]
Vertical stacking
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking
 [[1 2 5 6]
 [3 4 7 8]]
